# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlAuth0 < Formula
  desc "Sign in k8s cluster using auth0"
  homepage "https://github.com/KMConner/kubectl-auth0"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KMConner/kubectl-auth0/releases/download/v0.1.1/kubectl-auth0_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "75e4ce74fd83f6a839046eada863e5d5450f3f20ead3650d6a947bbeb180d949"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KMConner/kubectl-auth0/releases/download/v0.1.1/kubectl-auth0_0.1.1_Linux_x86_64.tar.gz"
      sha256 "b5bbae004fdbfc5153b5b4fc76963a1e864ca37cfe57de72fb0a606f22d310bb"
    end
  end

  def install
    bin.install "kubectl-auth0"
  end
end
